name: iOS CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.5'

      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x

      - name: Set up Xcode
        run: |
          xcversion select 11.2.1 --symlink
          sudo xcode-select --switch /Applications/Xcode_11.2.1.app/Contents/Developer

      - run: swift --version

      - name: flutter doctor
        run: |
          cd $FLUTTER_HOME
          flutter doctor
      - name: set up code
        run: |
          git clone git@github.com:${GIT_OWNER}/${GIT_REPO}.git
        env:
          GIT_OWNER: ${{secrets.GIT_OWNER}}
          GIT_REPO: ${{secrets.GIT_REPO}}

      - name: Build app
        run: |
          ln -s $FLUTTER_HOME/.pub-cache $HOME/.pub-cache
          cd ${GIT_REPO}
          flutter pub get
          flutter build ios --no-pub --flavor development --release --no-codesign --target lib/main_dev.dart > build.log
        timeout-minutes: 60
        env:
          GIT_REPO: ${{secrets.GIT_REPO}}
