name: preview

on:
  repository_dispatch:
    types: [preview-command]
# https://github.com/peter-evans/slash-command-dispatch-processor/blob/master/.github/workflows/hello-world-pr-command.yml
jobs:
  preview-ios:
    runs-on: macos-latest
    steps:
      - name: pending
        uses: amondnet/actions-status-updater@v1
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          action: update_state
          owner: ${{ github.event.client_payload.github.payload.repository.owner.login }}
          repo: ${{ github.event.client_payload.github.payload.repository.name }}
          ref: ${{ github.event.client_payload.pull_request.head.sha }}
          state: pending
          context: Preview
          description: "Commit status with target URL"
          url: "https://github.com/${GITHUB_REPOSITORY}/actions/runs"

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            >preview https://github.com/${GITHUB_REPOSITORY}/actions/runs
          reaction-type: heart
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.5'

      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x

      - name: Set up Xcode
        run: |
          xcversion select 11.2.1 --symlink
          sudo xcode-select --switch /Applications/Xcode_11.2.1.app/Contents/Developer
      - run: swift --version

      - name: flutter doctor
        run: |
          cd $FLUTTER_HOME
          flutter doctor

      - name: Build app
        run: |
          ln -s $FLUTTER_HOME/.pub-cache $HOME/.pub-cache
          flutter pub get
          flutter build ios --no-pub --flavor development --release --no-codesign --target lib/main_dev.dart > build.log
        timeout-minutes: 60

      - name: deploy to Firebase
        run: |
          cd ios
          echo "=== install firebase.tools ==="
          curl -sL firebase.tools | bash
          echo "=== install bundler ==="
          gem install bundler && bundle install --path vendor/bundle
          echo "=== install fastlane plugins ==="
          brew install getsentry/tools/sentry-cli
          fastlane install_plugins
          fastlane beta_dev service:GithubActions upload:true
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Add reaction
        if: success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: +1

      - name: success
        if: success()
        uses: amondnet/actions-status-updater@v1
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          action: update_state
          owner: ${{ github.event.client_payload.github.payload.repository.owner.login }}
          repo: ${{ github.event.client_payload.github.payload.repository.name }}
          ref: ${{ github.event.client_payload.pull_request.head.sha }}
          state: success
          context: Preview
          description: "Commit status with target URL"
          url: "https://github.com/${GITHUB_REPOSITORY}/actions/runs"


      - name: failure
        if: failure()
        uses: amondnet/actions-status-updater@v1
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          action: update_state
          owner: ${{ github.event.client_payload.github.payload.repository.owner.login }}
          repo: ${{ github.event.client_payload.github.payload.repository.name }}
          ref: ${{ github.event.client_payload.pull_request.head.sha }}
          state: failure
          context: Preview
          description: "Commit status with target URL"
          url: "https://github.com/${GITHUB_REPOSITORY}/actions/runs"

      - name: Add reaction
        if: failure()
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: -1